import { deepFreeze } from "./immutability";
import type { ProductionRecipe } from "./types";

const recipes: ProductionRecipe[] = [
  {
    recipeKey: "caleb.book_purchased.v1",
    revisionId: "c4010000-0000-4000-8000-000000000001",
    revisionNumber: 1,
    runtime: "automation_v2",
    derivedFromSnapshotId: "c1100000-0000-4000-8000-000000000001",
    deviationCodes: [
      "replace_duplicate_order_triggers",
      "replace_tags_with_line_item_state",
      "create_manual_fulfillment_task",
      "gate_nurture_on_marketing_eligibility",
    ],
    trigger: {
      type: "commerce.line_item_paid",
      productKind: "physical",
      scope: "line_item",
      requiresPendingFulfillment: true,
    },
    steps: [
      { key: "create-manual-fulfillment", type: "task.create", taskKind: "manual_physical_fulfillment" },
      { key: "send-book-order-message", type: "transactional_template.send", templateKey: "caleb-book-order-confirmed" },
      { key: "preserve-six-minute-handoff", type: "delay", delayMinutes: 6 },
      {
        key: "enter-book-nurture",
        type: "campaign_sequence.enter",
        campaignRecipeKey: "caleb.book_nurture.v1",
        condition: "marketing_eligible",
      },
    ],
    operationalState: "inactive",
    reviewState: "draft",
    workingRevisionId: "c4010000-0000-4000-8000-000000000001",
    approvedRevisionId: null,
    activeRevisionId: null,
    activationRequiresHumanApproval: true,
  },
  {
    recipeKey: "caleb.book_nurture.v1",
    revisionId: "c4010000-0000-4000-8000-000000000002",
    revisionNumber: 1,
    runtime: "campaigns",
    derivedFromSnapshotId: "c1100000-0000-4000-8000-000000000002",
    deviationCodes: [
      "remove_duplicate_order_triggers",
      "replace_unrelated_subjects",
      "replace_preview_links",
      "remove_unsupported_urgency",
      "enforce_marketing_policy_per_send",
    ],
    trigger: {
      type: "campaign_sequence.entered",
      sourceRecipeKey: "caleb.book_purchased.v1",
      sourceActionKey: "enter-book-nurture",
      scope: "customer_and_order",
    },
    steps: [
      { key: "wait-six-hours", type: "delay", delayMinutes: 360 },
      { key: "send-nurture-2", type: "campaign_template.send", templateKey: "caleb-book-nurture-2" },
      { key: "wait-one-day-1", type: "delay", delayMinutes: 1_440 },
      { key: "send-nurture-3", type: "campaign_template.send", templateKey: "caleb-book-nurture-3" },
      { key: "wait-two-days", type: "delay", delayMinutes: 2_880 },
      { key: "send-nurture-4", type: "campaign_template.send", templateKey: "caleb-book-nurture-4" },
      { key: "wait-one-day-2", type: "delay", delayMinutes: 1_440 },
      { key: "send-nurture-5", type: "campaign_template.send", templateKey: "caleb-book-nurture-5" },
      { key: "wait-one-day-3", type: "delay", delayMinutes: 1_440 },
      { key: "send-nurture-6", type: "campaign_template.send", templateKey: "caleb-book-nurture-6" },
      { key: "wait-one-day-4", type: "delay", delayMinutes: 1_440 },
      { key: "send-nurture-7", type: "campaign_template.send", templateKey: "caleb-book-nurture-7" },
      { key: "wait-final-day", type: "delay", delayMinutes: 1_440 },
      { key: "complete-sequence", type: "campaign_sequence.complete" },
    ],
    operationalState: "inactive",
    reviewState: "draft",
    workingRevisionId: "c4010000-0000-4000-8000-000000000002",
    approvedRevisionId: null,
    activeRevisionId: null,
    activationRequiresHumanApproval: true,
  },
  {
    recipeKey: "caleb.audiobook_purchased.v1",
    revisionId: "c4010000-0000-4000-8000-000000000003",
    revisionNumber: 1,
    runtime: "automation_v2",
    derivedFromSnapshotId: "c1100000-0000-4000-8000-000000000003",
    deviationCodes: ["replace_drive_link", "remove_cross_workflow_wait", "use_line_item_entitlement"],
    trigger: { type: "commerce.line_item_paid", productKind: "digital_download", productStableKey: "caleb-audiobook", scope: "line_item" },
    steps: [
      { key: "grant-audiobook", type: "commerce.product_entitlement.grant", entitlementScope: "line_item" },
      { key: "send-audiobook-access", type: "transactional_template.send", templateKey: "caleb-audiobook-access", routeKind: "passwordless_library" },
    ],
    operationalState: "inactive",
    reviewState: "draft",
    workingRevisionId: "c4010000-0000-4000-8000-000000000003",
    approvedRevisionId: null,
    activeRevisionId: null,
    activationRequiresHumanApproval: true,
  },
  {
    recipeKey: "caleb.course_purchased.v1",
    revisionId: "c4010000-0000-4000-8000-000000000004",
    revisionNumber: 1,
    runtime: "automation_v2",
    derivedFromSnapshotId: "c1100000-0000-4000-8000-000000000004",
    deviationCodes: ["replace_highlevel_offer", "replace_membership_login", "use_line_item_entitlement"],
    trigger: { type: "commerce.line_item_paid", productKind: "course", productStableKey: "caleb-course", scope: "line_item" },
    steps: [
      { key: "grant-course", type: "commerce.product_entitlement.grant", entitlementScope: "line_item" },
      { key: "preserve-one-minute-wait", type: "delay", delayMinutes: 1 },
      { key: "send-course-access", type: "transactional_template.send", templateKey: "caleb-course-access", routeKind: "passwordless_library" },
    ],
    operationalState: "inactive",
    reviewState: "draft",
    workingRevisionId: "c4010000-0000-4000-8000-000000000004",
    approvedRevisionId: null,
    activeRevisionId: null,
    activationRequiresHumanApproval: true,
  },
  {
    recipeKey: "caleb.workbook_purchased.v1",
    revisionId: "c4010000-0000-4000-8000-000000000005",
    revisionNumber: 1,
    runtime: "automation_v2",
    derivedFromSnapshotId: "c1100000-0000-4000-8000-000000000005",
    deviationCodes: ["replace_drive_link", "do_not_invent_missing_tag", "use_line_item_entitlement"],
    trigger: { type: "commerce.line_item_paid", productKind: "digital_download", productStableKey: "caleb-workbook", scope: "line_item" },
    steps: [
      { key: "grant-workbook", type: "commerce.product_entitlement.grant", entitlementScope: "line_item" },
      { key: "send-workbook-access", type: "transactional_template.send", templateKey: "caleb-workbook-access", routeKind: "passwordless_library" },
    ],
    operationalState: "inactive",
    reviewState: "draft",
    workingRevisionId: "c4010000-0000-4000-8000-000000000005",
    approvedRevisionId: null,
    activeRevisionId: null,
    activationRequiresHumanApproval: true,
  },
];

export const PRODUCTION_RECIPES: ProductionRecipe[] = deepFreeze(recipes);
